FROM debian:bullseye

RUN apt-get update && apt-get install -y circos-tools liblist-moreutils-perl procps

# Circos visualizes data in a circular layout — ideal for exploring relationships between objects or positions, and creating highly informative publication-quality graphics.

# This package provides a set of tools to help process your data: binlinks, bundlelinks, categoryviewer, colorinterpolate, filterlinks, maketutorialimages, orderchr, randomlinks, resample, and tableviewer.

# These tools are installed under: /usr/share/circos/tools

# Invoked as: `/usr/share/circos/tools/bundlelinks/bin/bundlelinks --help`

# v0.23-1_ps includes the procps package to allow collection of task metrics.